#include <cstdlib>
#include <iostream>
#include <fstream>

#include <cmath>

 

using namespace std;
 

int main() 
{

	ifstream dataInput;
	ofstream dataOutput;
	std::string tmpStr;

	const unsigned NTRY = 500;
	const unsigned n = 4;	//nb states
	const unsigned m = 2;	//nb measures

	// Matlab format
	selectKVectorContext(createKVectorContext(" ", "[ ", " ];", 4));
	selectKMatrixContext(createKMatrixContext(" ", " ;\n  ", "[ ", " ];", 4));

	 
	dataInput.open("../Matlab/data.m",ifstream::in);
	dataOutput.open("../Matlab/trajectory_udu_load.m", ofstream::out | ofstream::trunc);

	if (dataInput.fail())
	{
		cout<<"Unable to open input file!"<<endl;
		return 0;
	}

	if (dataOutput.fail())
	{
		cout<<"Unable to open output file!"<<endl;
		return 0;
	}

	cout<<"Loading inputs and measures from file <data.m>."<<endl;

	//Read the inputs vector. This vector have been generated by the Matlab script <generation.m>
	 

	if (dataInput.fail())
	{
		cout<<"IO error!"<<endl;
		return 0;
	}

	 
	dataOutput << "xxxx(" << ":," << 1 << ") = " << 6 << endl;

	dataOutput.close();
	dataInput.close();

	return EXIT_SUCCESS;
}
